export const historicalLandmarks = [
    {
        name: "Barasoain Church",
        id: 1,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Church",
        latitude: 14.84646279,
        longitude: 120.8126497,
    },
    {
        name: "Basilica Minore de Immaculada Concepcion",
        id: 2,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Church",
        latitude: 14.84298357,
        longitude: 120.8115019,
    },
    {
        name: "Bautista Mansion",
        id: 3,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.84270054,
        longitude: 120.8104554,
    },
    {
        name: "Cojuangco House",
        id: 4,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.84500138,
        longitude: 120.8126748,
    },
    {
        name: "Gen. Isodoro Torres Marker",
        id: 5,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.84301953,
        longitude: 120.8121215,
    },
    {
        name: "Instituto de Mujeres",
        id: 6,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.8426084,
        longitude: 120.8096216,
    },
    {
        name: "Kamestisuhan/ Calle Paranchillo",
        id: 7,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.841805,
        longitude: 120.8105982,
    },
    {
        name: "Siar Tree",
        id: 8,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.84289295,
        longitude: 120.8116524,
    },
    {
        name: "Reyes House",
        id: 9,
        city: "CITY OF MALOLOS",
        categoryMain: "HISTORY AND CULTURE",
        categorySub: "Landmark",
        latitude: 14.8422209,
        longitude: 120.8102771,
    },
];