import { LandmarkType } from "../model/landmark.types";

export const LANDMARK_TYPES = ['Caves',
    'Historic Monuments',
    'Religious Site',
    'Historical Cultural Attraction',
    'Museum',
    'Cultural Heritage',
    'Church',
    'Farm / Ranch',
    'Monument',
    'Structure & Buildings',
    'Fluvial Restaurant',
    'Historical Road/Trails',
    'Natural Attraction',
    'Malls',
    'Archaeological/Historic Sites',
    'Coastal Landscape and Seascape',
    'PARK/ BOTANICAL GARDEN',
    'CHURCH/RELIGIOUS SITE',
    'River and Landscape',
    'RESORT',
    'Structures and Buildings',
    'Falls',
    'Mountains/Hills/Highlands',
    'Unique Natural Landscape / Seascape',
    'Unique Cultural Heritage',
    'Other',
] satisfies LandmarkType[]