
  create table "public"."landmark_opening_hours" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "landmark_id" bigint not null,
    "day_of_week" smallint not null default '0'::smallint,
    "is_closed" boolean not null default false,
    "opens_at" time with time zone,
    "closes_at" time with time zone
      );


alter table "public"."landmark_opening_hours" enable row level security;

CREATE UNIQUE INDEX landmark_opening_hours_pkey ON public.landmark_opening_hours USING btree (id);

alter table "public"."landmark_opening_hours" add constraint "landmark_opening_hours_pkey" PRIMARY KEY using index "landmark_opening_hours_pkey";

alter table "public"."landmark_opening_hours" add constraint "landmark_opening_hours_landmark_id_fkey" FOREIGN KEY (landmark_id) REFERENCES public.landmark(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."landmark_opening_hours" validate constraint "landmark_opening_hours_landmark_id_fkey";

grant delete on table "public"."landmark_opening_hours" to "anon";

grant insert on table "public"."landmark_opening_hours" to "anon";

grant references on table "public"."landmark_opening_hours" to "anon";

grant select on table "public"."landmark_opening_hours" to "anon";

grant trigger on table "public"."landmark_opening_hours" to "anon";

grant truncate on table "public"."landmark_opening_hours" to "anon";

grant update on table "public"."landmark_opening_hours" to "anon";

grant delete on table "public"."landmark_opening_hours" to "authenticated";

grant insert on table "public"."landmark_opening_hours" to "authenticated";

grant references on table "public"."landmark_opening_hours" to "authenticated";

grant select on table "public"."landmark_opening_hours" to "authenticated";

grant trigger on table "public"."landmark_opening_hours" to "authenticated";

grant truncate on table "public"."landmark_opening_hours" to "authenticated";

grant update on table "public"."landmark_opening_hours" to "authenticated";

grant delete on table "public"."landmark_opening_hours" to "service_role";

grant insert on table "public"."landmark_opening_hours" to "service_role";

grant references on table "public"."landmark_opening_hours" to "service_role";

grant select on table "public"."landmark_opening_hours" to "service_role";

grant trigger on table "public"."landmark_opening_hours" to "service_role";

grant truncate on table "public"."landmark_opening_hours" to "service_role";

grant update on table "public"."landmark_opening_hours" to "service_role";


